// Verify all three deployed contracts on Etherscan in one shot.
//
// Reads the deployed addresses from frontend/src/config/contract.js
// (auto-generated by scripts/deploy.js) and runs `hardhat verify` for each
// contract in dependency order, passing the same constructor arguments
// the deploy script used.
//
// Usage:
//   npx hardhat run scripts/verify-all.js --network sepolia
//
// Requires ETHERSCAN_API_KEY in .env. Already-verified contracts are
// detected from the verifier's error message and reported as successes.

const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

const FRONTEND_CONFIG_PATH = path.join(
  __dirname,
  "..",
  "frontend",
  "src",
  "config",
  "contract.js"
);

const SEPARATOR = "=".repeat(60);

/**
 * frontend/src/config/contract.js is an ES module (the frontend's
 * package.json has `"type": "module"`), but this script runs in a
 * CommonJS Hardhat context where `require()` of ESM throws on older
 * Node versions. Parse the file as text instead — the format is
 * controlled by the deploy script so the regexes are stable.
 */
function readDeployedAddresses() {
  if (!fs.existsSync(FRONTEND_CONFIG_PATH)) {
    throw new Error(
      `frontend/src/config/contract.js does not exist. Run \`npm run deploy:sepolia\` first.`
    );
  }
  const text = fs.readFileSync(FRONTEND_CONFIG_PATH, "utf8");
  function extract(name) {
    const re = new RegExp(
      `export\\s+const\\s+${name}\\s*=\\s*["']([^"']+)["']`,
      "m"
    );
    const m = text.match(re);
    if (!m) {
      throw new Error(`Could not find ${name} in ${FRONTEND_CONFIG_PATH}`);
    }
    return m[1];
  }
  return {
    PATIENT_REGISTRY_ADDRESS:      extract("PATIENT_REGISTRY_ADDRESS"),
    CONSENT_MANAGER_ADDRESS:       extract("CONSENT_MANAGER_ADDRESS"),
    HEALTH_RECORD_STORAGE_ADDRESS: extract("HEALTH_RECORD_STORAGE_ADDRESS"),
  };
}

/**
 * Sepolia Etherscan URL for a deployed address.
 */
function etherscanUrl(address) {
  return `https://sepolia.etherscan.io/address/${address}#code`;
}

/**
 * Run verification for one contract, handling the "Already Verified"
 * case as a soft success.
 */
async function verifyOne(name, address, constructorArguments) {
  console.log();
  console.log(`Verifying ${name} @ ${address} ...`);
  try {
    await hre.run("verify:verify", {
      address,
      constructorArguments,
    });
    console.log(`${name}: verified ✓`);
    console.log(`  ${etherscanUrl(address)}`);
    return "verified";
  } catch (err) {
    const msg = (err && err.message) || String(err);
    // hardhat-verify surfaces this exact phrase (case may vary across
    // plugin versions) when the contract bytecode is already verified.
    if (/already verified/i.test(msg)) {
      console.log(`${name}: already verified ✓`);
      console.log(`  ${etherscanUrl(address)}`);
      return "alreadyVerified";
    }
    console.error(`${name}: verification FAILED`);
    console.error(`  ${msg}`);
    return "failed";
  }
}

async function main() {
  console.log(SEPARATOR);
  console.log("Verify Health Data Platform contracts on Etherscan");
  console.log(SEPARATOR);
  console.log("Network :", hre.network.name);

  if (hre.network.name === "hardhat" || hre.network.name === "localhost") {
    throw new Error(
      `Cannot verify on the ${hre.network.name} network. Pass --network sepolia.`
    );
  }

  const {
    PATIENT_REGISTRY_ADDRESS,
    CONSENT_MANAGER_ADDRESS,
    HEALTH_RECORD_STORAGE_ADDRESS,
  } = readDeployedAddresses();

  console.log("PatientRegistry      :", PATIENT_REGISTRY_ADDRESS);
  console.log("ConsentManager       :", CONSENT_MANAGER_ADDRESS);
  console.log("HealthRecordStorage  :", HEALTH_RECORD_STORAGE_ADDRESS);

  const results = [];

  // 1. PatientRegistry — no constructor args.
  results.push(
    await verifyOne("PatientRegistry", PATIENT_REGISTRY_ADDRESS, [])
  );

  // 2. ConsentManager — depends on PatientRegistry.
  results.push(
    await verifyOne("ConsentManager", CONSENT_MANAGER_ADDRESS, [
      PATIENT_REGISTRY_ADDRESS,
    ])
  );

  // 3. HealthRecordStorage — depends on both.
  results.push(
    await verifyOne("HealthRecordStorage", HEALTH_RECORD_STORAGE_ADDRESS, [
      PATIENT_REGISTRY_ADDRESS,
      CONSENT_MANAGER_ADDRESS,
    ])
  );

  const verifiedCount = results.filter(
    (r) => r === "verified" || r === "alreadyVerified"
  ).length;
  const failedCount = results.filter((r) => r === "failed").length;

  console.log();
  console.log(SEPARATOR);
  console.log(`Verification complete. ${verifiedCount}/3 contracts verified.`);
  if (failedCount > 0) {
    console.log(`${failedCount} contract(s) failed — see errors above.`);
  }
  console.log(SEPARATOR);

  if (failedCount > 0) {
    process.exitCode = 1;
  }
}

main()
  .then(() => process.exit(process.exitCode ?? 0))
  .catch((err) => {
    console.error();
    console.error("verify-all.js failed:");
    console.error(err);
    process.exit(1);
  });
